libary/urls.py
from django.urls import path
from libary import views

app_name = 'libary'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # CRUD - BOOK
    path('book/<int:book_id>/', views.book, name='book'),
    path('book/create/', views.create, name='create'),
    path('book/<int:book_id>/update/', views.update, name='update'),
    path('book/<int:book_id>/delete/', views.delete, name='delete'),

    # CRUD - USER
    path('user/', views.user_read, name='user_read'),
    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('libary.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

libary/models.py
from django.db import models

# Create your models here.


class Book_type(models.Model):
    type = models.CharField(max_length=200)

    def __str__(self):
        return self.type


class Genre(models.Model):
    genre = models.CharField(max_length=200)

    def __str__(self):
        return self.genre

# Collection - tabela que armazena os livros


class Collection(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    author = models.CharField(max_length=200, verbose_name='Autor')
    year = models.IntegerField(blank=True, verbose_name='Ano de lançamento')
    isbn = models.CharField(max_length=20, blank=True, verbose_name='ISBN')
    picture = models.ImageField(
        upload_to='book_pictures/%Y/%m', verbose_name='Imagem', blank=True)
    book_count = models.IntegerField(verbose_name='Livros em Estoque')
    description = models.TextField(blank=True, verbose_name='Descrição')
    type = models.ForeignKey(
        # type - tipo do material (livro, revista, jornal, etc)
        Book_type, on_delete=models.SET_NULL, null=True, verbose_name='Tipo')
    # genre - genero do livro
    # tem que salvar uma lista de generos
    genre = models.ForeignKey(
        Genre, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Gênero')

    def __str__(self):
        return self.title

libary/forms.py
from django import forms
from libary.models import Collection
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


class BookForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(attrs={'accept': 'image/*'}))

    class Meta:
        model = Collection
        fields = 'title', 'author', 'type', 'year', 'genre', 'book_count', 'isbn', 'description', 'picture',

    def clean(self):

        return super().clean()


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Nome')
    last_name = forms.CharField(
        max_length=30, required=True, label='Sobrenome')
    email = forms.EmailField(max_length=254, required=True)

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'username', 'password1', 'password2',

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error('email', ValidationError(
                'Este email já está em uso.', code='invalid'))

        return email


class ResgisteUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )
    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'username',

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )
        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error('email', ValidationError(
                    'Este email já está em uso.', code='invalid'))

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )
        return password1

libary/views/forms_views.py
from django.shortcuts import render, redirect, get_object_or_404
from libary.models import Collection
from django.urls import reverse
from libary.forms import BookForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='libary:login')
def create(request):
    form_action = reverse('libary:create')
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        context = {'form': form,
                   'form_action': form_action
                   }

        if form.is_valid():
            book = form.save()
            return redirect('libary:update', book_id=book.pk)

        return render(request, 'libary/create.html', context)

    context = {'form': BookForm(),
               'form_action': form_action
               }
    return render(request, 'libary/create.html', context)


@login_required(login_url='libary:login')
def update(request, book_id):
    book = get_object_or_404(Collection, pk=book_id)
    form_action = reverse('libary:update', args=(book_id,))

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        context = {'form': form,
                   'form_action': form_action
                   }

        if form.is_valid():
            book = form.save()
            return redirect('libary:update', book_id=book.pk)

        return render(request, 'libary/create.html', context)

    context = {'form': BookForm(instance=book),
               'form_action': form_action
               }
    return render(request, 'libary/create.html', context)


@login_required(login_url='libary:login')
def delete(request, book_id):
    book = get_object_or_404(Collection, pk=book_id)
    book.delete()

    return redirect('libary:index')

libary/views/libary_views.py
from django.shortcuts import render, get_object_or_404, redirect
from libary.models import Collection
from django.db.models import Q
from django.contrib.auth.models import User


def index(request):
    collection = Collection.objects.all()
    context = {'collection': collection}
    return render(request, 'libary/index.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('libary:index')

    collection = Collection.objects.all().filter(Q(title__icontains=search_value))
    context = {'collection': collection}
    return render(request, 'libary/index.html', context)


def book(request, book_id):
    single_book = get_object_or_404(Collection, pk=book_id)
    context = {'book': single_book}
    return render(request, 'libary/book.html', context)


def user_read(request):
    users = User.objects.all()
    return render(request, 'libary/users.html', {'users': users})

libary/views/user_forms.py
from django.shortcuts import render, redirect
from libary.forms import RegisterForm, ResgisteUpdateForm
from django.contrib import messages, auth  # type: ignore
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário criado com sucesso.')

            return redirect('libary:login')

    return render(request, 'libary/register.html', {'form': form})


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso.')
            return redirect('libary:index')
        messages.error(request, 'Usuário ou senha inválidos.')

    return render(request, 'libary/login.html', {'form': form})


@login_required(login_url='libary:login')
def user_update(request):
    form = ResgisteUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(request, 'libary/update_user.html', {'form': form})

    form = ResgisteUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(request, 'libary/update_user.html', {'form': form})

    form.save()
    return redirect('libary:user_update')


@login_required(login_url='libary:login')
def logout_view(request):
    auth.logout(request)
    return redirect('libary:login')

libary/templates/libary/book.html
{% extends "global/base.html" %} {% block content %}
<section class="book-detail">
    {% if book.picture %}
        <img src="{{ book.picture.url }}" alt="{{ book.title }}" width="300px" />
    {% endif %}
    <div class="book_info">
        <h1>{{ book.title }}</h1>
        <p><b>Autor:</b> {{ book.author }}</p>
        <p><b>Tipo:</b> {{ book.type }}</p>
        <p><b>Ano de lançamento:</b> {{ book.year }}</p>
        <p><b>Gênero:</b> {{ book.genre }}</p>
        <p><b>Livros em Estoque:</b> {{ book.book_count }}</p>
        {% if book.isbn %}
        <p><b>ISBN:</b> {{ book.isbn }}</p> 
        {% endif %}
        {% if book.description %}
        <p><b>Descrição: </b>{{ book.description }}</p>
        {% endif %}
    </div>
    <div class='btns'>
        <a href="{% url "libary:update" book.id %}" class="btn btn-edit" type="button">Editar</a>
        <form action="{% url "libary:delete" book.id %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-delete" type="submit">Deletar</button>
        </form>
    </div>
</section>
{% endblock content %}

libary/templates/libary/create.html
{% extends "global/base.html" %}

{% block content %}
    <h1 class="content-title">Adicionar Livro</h1>

    <form 
        action="{{form_action}}" 
        method="POST" 
        class="form-addbook" 
        enctype="multipart/form-data"
    >

        {% csrf_token %}


        {% for field in form %}
        <div class="input-group">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}} 

            {{field.errors}}
        </div>
        {% endfor %}

        <button type="submit" class="btn create-book ">Adicionar Livro</button>

    </form>
    
{% endblock content %}

libary/templates/libary/index.html
{% extends "global/base.html" %} 
{% block content %}
  {% if collection %}
  <h1 class="content-title">Livros</h1>

  <div class="search">
    <form action="{% url "libary:search" %}" method="GET" class="search-form">
      <input
        type="search"
        class="search-input"
        placeholder="Busque por um livro."
        id="search"
        name="q"
        value="{{ request.GET.q.strip }}"
      />
    </form>

    <a href="{% url "libary:create" %}" class="btn add-book" type="button">Adicionar Livro</a>
  </div>

  <section class="collection">
    {% for book in collection %}
    <a class="book" href="{% url "libary:book" book.id %}">
      {% if book.picture %}
        <img src="{{ book.picture.url }}" alt="{{ book.title }}" width="200px" />
      {% endif %}
      <p>{{ book.title }}</p>
    </a>
    {% endfor %}
  </section>
  {% else %}
  <h1 class="content-title">Nenhum livro encontrado</h1>
  <a href="{% url "libary:create" %}"class="btn add-book" type="button">Adicionar Livro</a>
  {% endif %}
{% endblock content %}

libary/templates/libary/login.html
{% extends "global/base.html" %}

{% block content %}
    <h1 class="content-title">Login</h1>

    {% if user.is_authenticated %}
        <p class='user-loggedin'>Você está logado como {{user.username}}. <a href="{% url "libary:logout" %}">Clique aqui</a> para sair.</p>
    {% else %}
        {% include "libary/partials/_user-form.html" %}
    {% endif %}

    
{% endblock content %}

libary/templates/libary/register.html
{% extends "global/base.html" %}

{% block content %}
    <h1 class="content-title">Cadastrar Usuário</h1>

    {% include "libary/partials/_user-form.html" %}
    
{% endblock content %}

libary/templates/libary/update_user.html
{% extends "global/base.html" %}

{% block content %}
    <h1 class="content-title">Atualizar Usuário</h1>

    {% include "libary/partials/_user-form.html" %}
    
{% endblock content %}

libary/templates/libary/users.html
{% extends "global/base.html" %}


{% block content %}
    <h1 class="content-title">Lista de Usuários</h1>

    <ul class="list-users">
    {% for user in users %}
        <li>{{user}}</li>
    {% endfor %}
    </ul>
    
{% endblock content %}